import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import { Epilogue } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${epilogue.className} overflow-y-scroll scrollbar w-100`}>
        {children}
      </body>
    </html>
  );
}
